### ISSUE TITLE
[CN DateTimeV2] Bad cases with characters such as '早', '晚', '到', and Festivals

### ISSUE THREAD

**Issue by blazezhazha** [microsoft/Recognizers-Text#1414]
Hi,
I may find some bad cases in data_time recognition, and I split them into two classes. The code I use for testing is simple and shown below.
```python
from recognizers_date_time import DateTimeRecognizer
from recognizers_text import Culture, ModelResult


def test(text):
  recognizer = DateTimeRecognizer(Culture.Chinese)
  model = recognizer.get_datetime_model()
  result = model.parse(text)
  if result:
    for r in result:
      print(r.start, r.end, r.text, r.resolution, r.type_name)
```
#### 1. About '早', '晚', '到'
First, I figure that, when phrases including those three words occur in a sentence, the `parse` function will sometimes throw an error.
For instance, here are some test sentences including phrases/words that contains the character '早':
```python
text1 = '最早去普吉岛的是什么时候'
text2 = '他们官网上明天早上这几班没有取消'
text3 = '我是十号从意大利到土耳其，电子签请务必早办妥'
text4 = '你好我6月15号一早的飞机，出了票了，来得及吗，申请了直接邮寄的方式'
text5 = '8.26的飞机飞泰国现在办早吗'
```
For each of those texts, I run `test` and always get a `KeyError: 'left'`. For `text4`, for example, the complete traceback is:
```shell
Traceback (most recent call last):
  File ".../date_normalize_test.py", line 76, in <module>
    test(text2)
  File ".../date_normalize_test.py", line 18, in test
    result = model.parse(text)
  File "...\recognizers-text\python\libraries\recognizers-date-time\recognizers_date_time\date_time\models.py", line 30, in parse
    parse_result = self.parser.parse(result, reference)
  File "...\recognizers-text\python\libraries\recognizers-date-time\recognizers_date_time\date_time\chinese\merged_parser.py", line 55, in parse
    result = self.config.date_time_period_parser.parse(source, reference)
  File "...\recognizers-text\python\libraries\recognizers-date-time\recognizers_date_time\date_time\chinese\datetimeperiod_parser.py", line 36, in parse
    inner_result = self.merge_date_and_time_periods(source_text, reference)
  File "...\recognizers-text\python\libraries\recognizers-date-time\recognizers_date_time\date_time\chinese\datetimeperiod_parser.py", line 68, in merge_date_and_time_periods
    pr_timeperiod = self.config.time_period_parser.parse(er_timeperiod, reference)
  File "...\recognizers-text\python\libraries\recognizers-date-time\recognizers_date_time\date_time\chinese\timeperiod_parser.py", line 38, in parse
    inner_result = self.parse_time_period(extra, reference)
  File "...\recognizers-text\python\libraries\recognizers-date-time\recognizers_date_time\date_time\chinese\timeperiod_parser.py", line 109, in parse_time_period
    left_entity = next(iter(extra.named_entity['left']), '')
KeyError: 'left'
```
When I remove '一早' from `text4` to get `_text4` and run `test(_text4)`, the result is correct.
```python
_text4 = '你好我6月15号的飞机，出了票了，来得及吗，申请了直接邮寄的方式'
```
```shell
3 7 6月15号 {'values': [{'timex': 'XXXX-06-15', 'type': 'date', 'value': '2018-06-15'}, {'timex': 'XXXX-06-15', 'type': 'date', 'value': '2019-06-15'}]} datetimeV2.date
```
And when I add '8点' behind '一早' to get `text4_` and run `test(text4_)`, the result is also right.
```python
text4_ = '你好我6月15号一早8点的飞机，出了票了，来得及吗，申请了直接邮寄的方式'
```
```shell
3 7 6月15号 {'values': [{'timex': 'XXXX-06-15', 'type': 'date', 'value': '2018-06-15'}, {'timex': 'XXXX-06-15', 'type': 'date', 'value': '2019-06-15'}]} datetimeV2.date
9 11 早8点 {'values': [{'timex': 'T08', 'type': 'time', 'value': '08:00:00'}]} datetimeV2.time
```
Sorry I have not read the internal code, but I still can infer the code supposes that '早' should appear in the text together with some __TIK-TOK TIME__.
'晚' cases is much as similar as '早' cases.
For '到', the problem occurs when phrases other than __ANOTHER DATE__ , such as a city name, is after the date before '到'. For instance,
```python
text6 = '我是7月4日到达北京，请问我选日期是什么时候？'
text6_ = '我是7月4日到7月6日去北京，请问我选日期是什么时候？'
```
the results are,
```shell
Traceback (most recent call last):
  File ".../date_normalize_test.py", line 78, in <module>
    test(text6)
  File ".../date_normalize_test.py", line 18, in test
    result = model.parse(text)
  File "...\recognizers-text\python\libraries\recognizers-date-time\recognizers_date_time\date_time\models.py", line 30, in parse
    parse_result = self.parser.parse(result, reference)
  File "...\recognizers-text\python\libraries\recognizers-date-time\recognizers_date_time\date_time\chinese\merged_parser.py", line 51, in parse
    result = self.config.date_period_parser.parse(source, reference)
  File "...\recognizers-text\python\libraries\recognizers-date-time\recognizers_date_time\date_time\chinese\dateperiod_parser.py", line 38, in parse
    inner_result = self._parse_simple_cases(source_text, reference)
  File "...\recognizers-text\python\libraries\recognizers-date-time\recognizers_date_time\date_time\chinese\dateperiod_parser.py", line 105, in _parse_simple_cases
    end_day = self.config.day_of_month[days[1]]
KeyError: ''


2 10 7月4日到7月6日 {'values': [{'timex': '(XXXX-07-04,XXXX-07-06,P2D)', 'type': 'daterange', 'start': '2018-07-04', 'end': '2018-07-06'}, {'timex': '(XXXX-07-04,XXXX-07-06,P2D)', 'type': 'daterange', 'start': '2019-07-04', 'end': '2019-07-06'}]} datetimeV2.daterange
```
#### 2. About Festival
Besides, when a Chinese festival is included in the text, there is always a `TypeError` as follows
```python
text7 = '你们春节前的8号去 什么时候回'
```
```shell
Traceback (most recent call last):
  File ".../date_normalize_test.py", line 78, in <module>
    test(text6)
  File ".../date_normalize_test.py", line 18, in test
    result = model.parse(text)
  File "...\recognizers-text\python\libraries\recognizers-date-time\recognizers_date_time\date_time\models.py", line 30, in parse
    parse_result = self.parser.parse(result, reference)
  File "...\recognizers-text\python\libraries\recognizers-date-time\recognizers_date_time\date_time\chinese\merged_parser.py", line 43, in parse
    result = self.config.date_parser.parse(source, reference)
  File "...\recognizers-text\python\libraries\recognizers-date-time\recognizers_date_time\date_time\chinese\date_parser.py", line 40, in parse
    inner_result = self.parse_weekday_of_month(source_text, reference)
  File "...\recognizers-text\python\libraries\recognizers-date-time\recognizers_date_time\date_time\base_date.py", line 642, in parse_weekday_of_month
    match = regex.match(self.config.week_day_of_month_regex, trimmed_source)
  File "...\lib\site-packages\regex.py", line 251, in match
    return _compile(pattern, flags, kwargs).match(string, pos, endpos,
  File "...\lib\site-packages\regex.py", line 483, in _compile
    raise TypeError("first argument must be a string or compiled pattern")
TypeError: first argument must be a string or compiled pattern
```
Known festivals are:
春节 正月 新年 劳动节 清明  

---

Sorry about this  __LOOOOOOOOOONG__ issue, and I try to brief the cases I've met so far. Hope it help you fix them and complete this project.
Thank you all for this wonderful tool!

Blazezhazha

**Comment by FeifanLiu98** [comment]
Missing extraction "7月4日" of "我是7月4日到达北京，请问我选日期是什么时候？".
