### ISSUE TITLE
[JavaScript] Can't build on Ubuntu Linux due to the file name upper/lowercase mismatches

### ISSUE THREAD

**Issue by combacsa** [microsoft/Recognizers-Text#1773]
**Describe the bug**
Unlike Windows NTFS file system, on Linux, we need to ensure that file name must matches with its upper/lowercase status. If the filename is 'timexRegex.js', then we must not use 'timexregex.js' to open that file, since there is a upper/lowercase mismatch. 

I tried to build JavaScript package on my Ubuntu 18.04.2 LTS and failed. I found several module name upper/lowercase mismatches on the source code.

**To Reproduce**
0. Prepare Ubuntu Linux 18.04.2 installed.
1. Go to 'JavaScript' folder, by typing `cd JavaScript`, on the repository.
2. Execute `bash ./build.sh`
3. ....

**Expected behavior**
No error at all.

**Sample input/output**
```
npm run build

> recognizers@1.1.4 build /data/personal/Recognizers-Text/JavaScript
> lerna clean --yes && lerna bootstrap --hoist

lerna info version 2.11.0
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/recognizers-choice/node_modules
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/recognizers-date-time/node_modules
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/recognizers-number-with-unit/node_modules
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/recognizers-number/node_modules
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/recognizers-sequence/node_modules
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/recognizers-text-suite/node_modules
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/recognizers-text/node_modules
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/datatypes-date-time/node_modules
lerna success clean finished
lerna info version 2.11.0
lerna info Bootstrapping 8 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna info hoist Finished installing in root
lerna info Symlinking packages and binaries
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text is already installed for @microsoft/recognizers-text-choice. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text is already installed for @microsoft/recognizers-text-date-time. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-number is already installed for @microsoft/recognizers-text-date-time. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-number-with-unit is already installed for @microsoft/recognizers-text-date-time. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text is already installed for @microsoft/recognizers-text-number-with-unit. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-number is already installed for @microsoft/recognizers-text-number-with-unit. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text is already installed for @microsoft/recognizers-text-number. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text is already installed for @microsoft/recognizers-text-sequence. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text is already installed for @microsoft/recognizers-text-suite. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-number is already installed for @microsoft/recognizers-text-suite. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-number-with-unit is already installed for @microsoft/recognizers-text-suite. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-date-time is already installed for @microsoft/recognizers-text-suite. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-sequence is already installed for @microsoft/recognizers-text-suite. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-choice is already installed for @microsoft/recognizers-text-suite. Replacing with symlink...
lerna info lifecycle postinstall
lerna info lifecycle prepublish
lerna info lifecycle prepare
lerna ERR! execute Error occured with '@microsoft/recognizers-text-data-types-timex-expression' while running 'npm run prepare'
lerna ERR! npm run prepare [@microsoft/recognizers-text-data-types-timex-expression] Output from stdout:

> @microsoft/recognizers-text-data-types-timex-expression@1.1.4 prepare /data/personal/Recognizers-Text/JavaScript/packages/datatypes-date-time
> npm run clean-build && rollup -c


> @microsoft/recognizers-text-data-types-timex-expression@1.1.4 clean-build /data/personal/Recognizers-Text/JavaScript/packages/datatypes-date-time
> rimraf dist


lerna ERR! npm run prepare [@microsoft/recognizers-text-data-types-timex-expression] Output from stderr:

index.js → dist/recognizers-text-data-types-timex-expression.es5.js, dist/recognizers-text-data-types-timex-expression.umd.js, dist/recognizers-text-data-types-timex-expression.browser.js...
[!] Error: Could not resolve './timexregex.js' from src/timexParsing.js
Error: Could not resolve './timexregex.js' from src/timexParsing.js
    at error (/data/personal/Recognizers-Text/JavaScript/node_modules/rollup/dist/rollup.js:185:14)
    at then.resolvedId (/data/personal/Recognizers-Text/JavaScript/node_modules/rollup/dist/rollup.js:10124:8)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @microsoft/recognizers-text-data-types-timex-expression@1.1.4 prepare: `npm run clean-build && rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @microsoft/recognizers-text-data-types-timex-expression@1.1.4 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/khbyun/.npm/_logs/2019-08-05T13_08_17_419Z-debug.log

lerna ERR! execute Error occured with '@microsoft/recognizers-text-data-types-timex-expression' while running 'npm run prepare'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
{ Error: Command failed: npm run prepareplete Waiting for 1 child process to exit. CTRL-C to exit immediately.

index.js → dist/recognizers-text-data-types-timex-expression.es5.js, dist/recognizers-text-data-types-timex-expression.umd.js, dist/recognizers-text-data-types-timex-expression.browser.js...
[!] Error: Could not resolve './timexregex.js' from src/timexParsing.js
Error: Could not resolve './timexregex.js' from src/timexParsing.js
    at error (/data/personal/Recognizers-Text/JavaScript/node_modules/rollup/dist/rollup.js:185:14)
    at then.resolvedId (/data/personal/Recognizers-Text/JavaScript/node_modules/rollup/dist/rollup.js:10124:8)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @microsoft/recognizers-text-data-types-timex-expression@1.1.4 prepare: `npm run clean-build && rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @microsoft/recognizers-text-data-types-timex-expression@1.1.4 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/khbyun/.npm/_logs/2019-08-05T13_08_17_419Z-debug.log

> @microsoft/recognizers-text-data-types-timex-expression@1.1.4 prepare /data/personal/Recognizers-Text/JavaScript/packages/datatypes-date-time
> npm run clean-build && rollup -c


> @microsoft/recognizers-text-data-types-timex-expression@1.1.4 clean-build /data/personal/Recognizers-Text/JavaScript/packages/datatypes-date-time
> rimraf dist


    at Promise.all.then.arr (/data/personal/Recognizers-Text/JavaScript/node_modules/lerna/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  killed: false,
  stdout:
   '\n> @microsoft/recognizers-text-data-types-timex-expression@1.1.4 prepare /data/personal/Recognizers-Text/JavaScript/packages/datatypes-date-time\n> npm run clean-build && rollup -c\n\n\n> @microsoft/recognizers-text-data-types-timex-expression@1.1.4 clean-build /data/personal/Recognizers-Text/JavaScript/packages/datatypes-date-time\n> rimraf dist\n\n',
  stderr:
   '\nindex.js → dist/recognizers-text-data-types-timex-expression.es5.js, dist/recognizers-text-data-types-timex-expression.umd.js, dist/recognizers-text-data-types-timex-expression.browser.js...\n[!] Error: Could not resolve \'./timexregex.js\' from src/timexParsing.js\nError: Could not resolve \'./timexregex.js\' from src/timexParsing.js\n    at error (/data/personal/Recognizers-Text/JavaScript/node_modules/rollup/dist/rollup.js:185:14)\n    at then.resolvedId (/data/personal/Recognizers-Text/JavaScript/node_modules/rollup/dist/rollup.js:10124:8)\n\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! @microsoft/recognizers-text-data-types-timex-expression@1.1.4 prepare: `npm run clean-build && rollup -c`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the @microsoft/recognizers-text-data-types-timex-expression@1.1.4 prepare script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\nnpm WARN Local package.json exists, but node_modules missing, did you mean to install?\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/khbyun/.npm/_logs/2019-08-05T13_08_17_419Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'npm run prepare',
  timedOut: false,
  pkg:
   Package {
     _package:
      { name: '@microsoft/recognizers-text-data-types-timex-expression',
        version: '1.1.4',
        description: 'Support for TIMEX representation of data time',
        author: 'Microsoft',
        license: 'MIT',
        keywords: [Array],
        main: 'dist/recognizers-text-data-types-timex-expression.umd.js',
        module: 'dist/recognizers-text-data-types-timex-expression.es5.js',
        browser:
         'dist/recognizers-text-data-types-timex-expression.browser.js',
        repository: [Object],
        bugs: [Object],
        engines: [Object],
        scripts: [Object],
        devDependencies: [Object] },
     _location:
      '/data/personal/Recognizers-Text/JavaScript/packages/datatypes-date-time' },
  exitCode: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! recognizers@1.1.4 build: `lerna clean --yes && lerna bootstrap --hoist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the recognizers@1.1.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/khbyun/.npm/_logs/2019-08-05T13_08_20_500Z-debug.log
```

**Platform (please complete the following information):**
 - Platform: [JavaScript]
 - Environment: [Node v10.16.0]
 - Version of package [master branch]

**Additional context**
Would it be OK for me to try to create a pull request regarding this? Unfortunately I won't find easy way to check if it will work on Windows though.

**Comment by combacsa** [comment]
Made a Pull Request #1774 to solve this problem. Please do not hesitate to take a look.
