### ISSUE TITLE
[EN .NET] TimexProperty.ToString() throws exception for datetimerange

### ISSUE THREAD

**Issue by shana** [microsoft/Recognizers-Text#2893]
**Describe the bug**

`new TimexProperty("(2022-03-15T16,2022-03-15T18,PT2H)").ToString()` throws the following exception:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
at Microsoft.Recognizers.Text.DataTypes.TimexExpression.TimexConvertEnglish.ConvertTimeRange(TimexProperty timex) in Recognizers-Text\.NET\Microsoft.Recognizers.Text.DataTypes.TimexExpression\English\TimexConvertEnglish.cs:line 206
at Microsoft.Recognizers.Text.DataTypes.TimexExpression.TimexConvertEnglish.ConvertDateTimeRange(TimexProperty timex) in Recognizers-Text\.NET\Microsoft.Recognizers.Text.DataTypes.TimexExpression\English\TimexConvertEnglish.cs:line 218
at Microsoft.Recognizers.Text.DataTypes.TimexExpression.TimexConvertEnglish.ConvertTimexToString(TimexProperty timex) in Recognizers-Text\.NET\Microsoft.Recognizers.Text.DataTypes.TimexExpression\English\TimexConvertEnglish.cs:line 22
at Microsoft.Recognizers.Text.DataTypes.TimexExpression.TimexConvert.ConvertTimexToString(TimexProperty timex) in Recognizers-Text\.NET\Microsoft.Recognizers.Text.DataTypes.TimexExpression\TimexConvert.cs:line 10
at Microsoft.Recognizers.Text.DataTypes.TimexExpression.TimexProperty.ToString() in Recognizers-Text\.NET\Microsoft.Recognizers.Text.DataTypes.TimexExpression\TimexProperty.cs:line 164
at Microsoft.Recognizers.Text.DataTypes.TimexExpression.Tests.TestTimex.DataTypes_Timex_FromDateTimeRange_ToString() in Recognizers-Text\.NET\Microsoft.Recognizers.Text.DataTypes.DataDrivenTests\TestTimex.cs:line 141
```
**Expected behavior**
It should return `"15th March 2022 4PM"`

**Platform (please complete the following information):**
 - Platform: .NET
 - Environment: nuget package
 - Version: v1.8.2

**Comment by tellarin** [comment]
Fixes cover the exception only, not the wrong text gen yet.
